name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Checks
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cargo install --force cargo-make
      - run: rustup component add rustfmt clippy
      - run: cargo make ci
